import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
// import styles from '../styles/Home.module.css'
import styled from 'styled-components';

import CalendarWebtoonItem from './calendar/components/calendarWebtoonItem';
import Calendar from './calendar';

const GlobalWrapper = styled.div`
  padding: 16px 0 0 0;
  max-width: 640px;
  // display: flex;
  // align-item: center;
  // flex-direction: column;
  margin: 0 0;
  margin-left: auto;
  margin-right: auto;
`;

const HeaderWrapper = styled.div`
  padding: 0 16px;

  height: 56px;
  width: 100%;
  display: flex;
  align-items: center;
  // background-color: blue;

  p,
  h1 {
    margin-left: 8px;
    font-style: normal;
    font-weight: 700;
    font-size: 18px;
    line-height: 26px;
  }
`;

const NavToggleWrapper = styled.div`
  display: flex;
  height: 48px;
  padding: 0 16px;
  cursor: pointer;

  .toggled {
    font-style: normal;
    font-weight: 700;
    font-size: 16px;
    line-height: 24px;
    color: #000000;

    border-bottom: 3px solid #000000;
  }

  .normal {
    font-style: normal;
    font-weight: 700;
    font-size: 16px;
    line-height: 24px;
    /* identical to box height, or 150% */

    display: flex;
    align-items: center;
    text-align: center;
    text-transform: uppercase;

    opacity: 0.3;

    color: #000000;
  }
`;

const NavIcon = styled.div`
  width: 50%;
  height: 48px;
  display: flex;
  align-items: center;
  justify-content: center;

  img {
    width: 16px;
    height: 18.59px;
  }
`;

const NavItem = styled.div`
  width: 50%;
  height: 48px;
  display: flex;
  align-items: center;
  justify-content: center;
`;

const Home: NextPage = () => {
  const [toggleMenu, setToggleMenu] = useState('calendar');

  const changeToggleMenu = (menu: string) => {
    setToggleMenu(menu);
  };

  return (
    <>
      <GlobalWrapper>
        <HeaderWrapper>
          <h1>Logo</h1>
        </HeaderWrapper>

        <NavToggleWrapper>
          {/* <NavIcon>
            <img src={`icons/home.png`} />
          </NavIcon> */}

          <NavItem onClick={() => changeToggleMenu('calendar')} className={toggleMenu === 'calendar' ? 'toggled' : 'normal'}>
            <p>유료화 일정</p>
          </NavItem>

          <NavItem onClick={() => changeToggleMenu('category')} className={toggleMenu === 'category' ? 'toggled' : 'normal'}>
            <p>장르별</p>
          </NavItem>



        
        </NavToggleWrapper>

          {toggleMenu === 'calendar' ? (
            <>
              <Calendar></Calendar>
            </>
          ) : (
            <></>
          )}
      </GlobalWrapper>
    </>
    // <div className={styles.container}>

    //  <Head>
    //   <title>Create Next App</title>
    //   <meta name="description" content="Generated by create next app" />
    //   <link rel="icon" href="/favicon.ico" />
    // </Head>

    // <main className={styles.main}>
    //   <h1 className={styles.title}>
    //     Welcome to <a href="https://nextjs.org">Next.js!</a>
    //   </h1>

    //   <p className={styles.description}>
    //     Get started by editing{' '}
    //     <code className={styles.code}>pages/index.tsx</code>
    //   </p>

    //   <div className={styles.grid}>
    //     <a href="https://nextjs.org/docs" className={styles.card}>
    //       <h2>Documentation &rarr;</h2>
    //       <p>Find in-depth information about Next.js features and API.</p>
    //     </a>

    //     <a href="https://nextjs.org/learn" className={styles.card}>
    //       <h2>Learn &rarr;</h2>
    //       <p>Learn about Next.js in an interactive course with quizzes!</p>
    //     </a>

    //     <a
    //       href="https://github.com/vercel/next.js/tree/canary/examples"
    //       className={styles.card}
    //     >
    //       <h2>Examples &rarr;</h2>
    //       <p>Discover and deploy boilerplate example Next.js projects.</p>
    //     </a>

    //     <a
    //       href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       className={styles.card}
    //     >
    //       <h2>Deploy &rarr;</h2>
    //       <p>
    //         Instantly deploy your Next.js site to a public URL with Vercel.
    //       </p>
    //     </a>
    //   </div>
    // </main>

    // <footer className={styles.footer}>
    //   <a
    //     href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //     target="_blank"
    //     rel="noopener noreferrer"
    //   >
    //     Powered by{' '}
    //     <span className={styles.logo}>
    //       <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //     </span>
    //   </a>
    // </footer>
    // </div>
  );
};

export default Home;
