import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
// import styles from '../styles/Home.module.css'
import styled from 'styled-components';

const GlobalWrapper = styled.div`
  padding: 16px;
`;

const HeaderWrapper = styled.div`
  height: 56px;
  width: 100%;
  display: flex;
  align-items: center;
  // background-color: blue;

  p,
  h1 {
    margin-left: 8px;
    font-style: normal;
    font-weight: 700;
    font-size: 18px;
    line-height: 26px;
  }
`;

const NavToggleWrapper = styled.div`
  display: flex;
  height: 48px;
`;

const NavIcon = styled.div`
  width: 48px;
  height: 48px;
  display: flex;
  align-items: center;
  justify-content: center;

  img {
    width: 16px;
    height: 18.59px;
  }
`;

const NavItem = styled.div`
  width: 74px;
  height: 48px;
  display: flex;
  align-items: center;
  justify-content: center;
`;

const CalendarInput = styled.input`
  width: 100%;
  height: 48px;

  margin-top: 16px;

  border: 1px solid #000000;
  box-sizing: border-box;
  border-radius: 4px;

  ::placeholder {
    padding: 12px;
    font-family: 'Pretendard';
    font-style: normal;
    font-weight: 400;
    font-size: 14px;
    line-height: 24px;

    display: flex;
    align-items: center;
    text-transform: uppercase;

    color: #c4c4c4;
  }
`;

const Home: NextPage = () => {
  return (
    <>
      <GlobalWrapper>
        <HeaderWrapper>
          <h1>Logo</h1>
        </HeaderWrapper>

        <NavToggleWrapper>
          <NavIcon>
            {/* <HomeIcon/> */}
            <img src={`icons/home.png`} />
          </NavIcon>

          <NavItem>
            <p>장르별</p>
          </NavItem>
        </NavToggleWrapper>

        <CalendarInput placeholder="웹툰명을 검색해주세요." />
      </GlobalWrapper>
    </>
    // <div className={styles.container}>

    //  <Head>
    //   <title>Create Next App</title>
    //   <meta name="description" content="Generated by create next app" />
    //   <link rel="icon" href="/favicon.ico" />
    // </Head>

    // <main className={styles.main}>
    //   <h1 className={styles.title}>
    //     Welcome to <a href="https://nextjs.org">Next.js!</a>
    //   </h1>

    //   <p className={styles.description}>
    //     Get started by editing{' '}
    //     <code className={styles.code}>pages/index.tsx</code>
    //   </p>

    //   <div className={styles.grid}>
    //     <a href="https://nextjs.org/docs" className={styles.card}>
    //       <h2>Documentation &rarr;</h2>
    //       <p>Find in-depth information about Next.js features and API.</p>
    //     </a>

    //     <a href="https://nextjs.org/learn" className={styles.card}>
    //       <h2>Learn &rarr;</h2>
    //       <p>Learn about Next.js in an interactive course with quizzes!</p>
    //     </a>

    //     <a
    //       href="https://github.com/vercel/next.js/tree/canary/examples"
    //       className={styles.card}
    //     >
    //       <h2>Examples &rarr;</h2>
    //       <p>Discover and deploy boilerplate example Next.js projects.</p>
    //     </a>

    //     <a
    //       href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       className={styles.card}
    //     >
    //       <h2>Deploy &rarr;</h2>
    //       <p>
    //         Instantly deploy your Next.js site to a public URL with Vercel.
    //       </p>
    //     </a>
    //   </div>
    // </main>

    // <footer className={styles.footer}>
    //   <a
    //     href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //     target="_blank"
    //     rel="noopener noreferrer"
    //   >
    //     Powered by{' '}
    //     <span className={styles.logo}>
    //       <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //     </span>
    //   </a>
    // </footer>
    // </div>
  );
};

export default Home;
